spring:
  application:
    name: EUREKA-SERVER
server:
  port: 8761 #this is default port or eureka server, we can change also.

eureka:
  client:
    register-with-eureka: false
    fetch-registery: false

